# Generated by Django 5.0.1 on 2025-12-28 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticscache',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_caches', to='core.location'),
        ),
        migrations.AddField(
            model_name='analyticscache',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_caches', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='analyticscache',
            index=models.Index(fields=['tenant', 'cache_type', 'expires_at'], name='analytics_c_tenant__54bac2_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticscache',
            index=models.Index(fields=['location'], name='analytics_c_locatio_0342c3_idx'),
        ),
    ]
