# Generated by Django 5.0.1 on 2025-12-28 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('negative_stock_behavior', models.CharField(choices=[('block', 'Block'), ('warn', 'Warn'), ('allow', 'Allow')], default='block', max_length=20)),
                ('track_batches', models.BooleanField(default=True)),
                ('track_expiry', models.BooleanField(default=False)),
                ('require_margin_check', models.BooleanField(default=True)),
                ('margin_check_behavior', models.CharField(choices=[('block', 'Block'), ('warn', 'Warn'), ('allow', 'Allow')], default='warn', max_length=20)),
                ('refund_approval_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Amount above which refunds require approval', max_digits=15, null=True)),
                ('enable_offline_mode', models.BooleanField(default=True)),
                ('allow_backdating', models.BooleanField(default=False)),
                ('backdating_days_limit', models.IntegerField(blank=True, default=7, null=True)),
                ('enable_audit_logs', models.BooleanField(default=True)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_sms_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_configurations',
            },
        ),
        migrations.CreateModel(
            name='WorkflowConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_name', models.CharField(max_length=100)),
                ('config_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflow_configurations',
            },
        ),
    ]
