# Generated by Django 5.0.1 on 2025-12-28 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_config', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='workflowconfiguration',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_configs', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='workflowconfiguration',
            index=models.Index(fields=['tenant', 'workflow_name', 'is_active'], name='workflow_co_tenant__f1ddb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowconfiguration',
            unique_together={('tenant', 'workflow_name')},
        ),
    ]
