# Generated by Django 5.0.1 on 2025-12-28 18:39

import django.core.validators
import django_fsm
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashUpReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_number', models.CharField(max_length=100, unique=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('state', django_fsm.FSMField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('closed', 'Closed')], default='draft', max_length=50, protected=True)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('expected_card', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('expected_mobile_money', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('expected_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('actual_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('actual_card', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('actual_mobile_money', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('actual_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('variance_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('variance_card', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('variance_mobile_money', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('variance_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('variance_explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cash_up_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remittance_number', models.CharField(max_length=100, unique=True)),
                ('state', django_fsm.FSMField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('closed', 'Closed')], default='submitted', max_length=50, protected=True)),
                ('amount_remitted', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('variance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('remittance_date', models.DateField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque')], default='cash', max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('variance_explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'remittances',
                'ordering': ['-created_at'],
            },
        ),
    ]
