# Generated by Django 5.0.1 on 2025-12-28 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashupreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cash_up_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashupreport',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_up_reports', to='sales.shift'),
        ),
        migrations.AddField(
            model_name='cashupreport',
            name='shop',
            field=models.ForeignKey(limit_choices_to={'location_type': 'shop'}, on_delete=django.db.models.deletion.PROTECT, related_name='cash_up_reports', to='core.location'),
        ),
        migrations.AddField(
            model_name='cashupreport',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cash_up_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashupreport',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_up_reports', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_remittances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remittance',
            name='cash_up_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='accounting.cashupreport'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_remittances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remittance',
            name='shop',
            field=models.ForeignKey(limit_choices_to={'location_type': 'shop'}, on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='core.location'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_remittances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remittance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='cashupreport',
            index=models.Index(fields=['tenant', 'state'], name='cash_up_rep_tenant__ef9a88_idx'),
        ),
        migrations.AddIndex(
            model_name='cashupreport',
            index=models.Index(fields=['shop'], name='cash_up_rep_shop_id_9f44c0_idx'),
        ),
        migrations.AddIndex(
            model_name='cashupreport',
            index=models.Index(fields=['report_number'], name='cash_up_rep_report__ed0038_idx'),
        ),
        migrations.AddIndex(
            model_name='cashupreport',
            index=models.Index(fields=['period_start', 'period_end'], name='cash_up_rep_period__4fd0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='remittance',
            index=models.Index(fields=['tenant', 'state'], name='remittances_tenant__4b909e_idx'),
        ),
        migrations.AddIndex(
            model_name='remittance',
            index=models.Index(fields=['shop'], name='remittances_shop_id_7667a1_idx'),
        ),
        migrations.AddIndex(
            model_name='remittance',
            index=models.Index(fields=['remittance_number'], name='remittances_remitta_3edcc7_idx'),
        ),
        migrations.AddIndex(
            model_name='remittance',
            index=models.Index(fields=['remittance_date'], name='remittances_remitta_b737df_idx'),
        ),
    ]
