# Generated by Django 5.0.1 on 2025-12-28 18:39

import django.core.validators
import django.db.models.deletion
import django_fsm
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.tenant')),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('state', django_fsm.FSMField(choices=[('active', 'Active'), ('over_limit', 'Over Limit'), ('delinquent', 'Delinquent'), ('suspended', 'Suspended')], default='active', max_length=50, protected=True)),
                ('payment_terms_days', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_accounts', to='core.tenant')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='sales.customer')),
            ],
            options={
                'db_table': 'credit_accounts',
            },
        ),
        migrations.CreateModel(
            name='MarginRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimum_margin_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('warning_margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('behavior', models.CharField(choices=[('block', 'Block'), ('warn', 'Warn'), ('allow', 'Allow')], default='warn', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='margin_rules', to='inventory.product')),
                ('shop', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'shop'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='margin_rules', to='core.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margin_rules', to='core.tenant')),
            ],
            options={
                'db_table': 'margin_rules',
            },
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('price_multiplier', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='inventory.product')),
                ('shop', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'shop'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='core.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='core.tenant')),
            ],
            options={
                'db_table': 'price_rules',
                'ordering': ['-priority', 'effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_number', models.CharField(max_length=100, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('state', django_fsm.FSMField(choices=[('completed', 'Completed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('voided', 'Voided')], default='completed', max_length=50, protected=True)),
                ('is_offline', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.customer')),
                ('shop', models.ForeignKey(limit_choices_to={'location_type': 'shop'}, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.tenant')),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_number', models.CharField(max_length=100, unique=True)),
                ('state', django_fsm.FSMField(choices=[('initiated', 'Initiated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='initiated', max_length=50, protected=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_refunds', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(limit_choices_to={'location_type': 'shop'}, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='core.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='core.tenant')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.sale')),
            ],
            options={
                'db_table': 'refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('card', 'Card'), ('credit_account', 'Credit Account')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'db_table': 'sale_items',
            },
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('classification', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('expired', 'Expired')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.refund')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_items', to='sales.saleitem')),
            ],
            options={
                'db_table': 'refund_items',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(limit_choices_to={'location_type': 'shop'}, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.tenant')),
            ],
            options={
                'db_table': 'shifts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.shift'),
        ),
        migrations.CreateModel(
            name='ShopProductCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_costs', to='inventory.batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_costs', to='inventory.product')),
                ('shop', models.ForeignKey(limit_choices_to={'location_type': 'shop'}, on_delete=django.db.models.deletion.CASCADE, related_name='product_costs', to='core.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_product_costs', to='core.tenant')),
            ],
            options={
                'db_table': 'shop_product_costs',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('payment', 'Payment'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='sales.creditaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='core.tenant')),
            ],
            options={
                'db_table': 'credit_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'credit_account'], name='credit_tran_tenant__37aac0_idx'), models.Index(fields=['transaction_type', 'reference_type', 'reference_id'], name='credit_tran_transac_2c565e_idx'), models.Index(fields=['created_at'], name='credit_tran_created_d7035f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'is_active'], name='customers_tenant__ac02c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['tenant', 'customer', 'is_active'], name='credit_acco_tenant__740f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['state'], name='credit_acco_state_8bc4f4_idx'),
        ),
        migrations.AddIndex(
            model_name='marginrule',
            index=models.Index(fields=['shop', 'product', 'is_active'], name='margin_rule_shop_id_a50ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='pricerule',
            index=models.Index(fields=['shop', 'product', 'is_active'], name='price_rules_shop_id_5d6baa_idx'),
        ),
        migrations.AddIndex(
            model_name='pricerule',
            index=models.Index(fields=['effective_from', 'effective_to'], name='price_rules_effecti_66c2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['tenant', 'state'], name='refunds_tenant__f65208_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['sale'], name='refunds_sale_id_336c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_number'], name='refunds_refund__a55d04_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sale', 'payment_method'], name='payments_sale_id_bf2b36_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='sale_items_sale_id_02f224_idx'),
        ),
        migrations.AddIndex(
            model_name='refunditem',
            index=models.Index(fields=['refund', 'sale_item'], name='refund_item_refund__a588ca_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['tenant', 'location', 'attendant'], name='shifts_tenant__f73e30_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['is_open'], name='shifts_is_open_1a3984_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'shop', 'attendant'], name='sales_tenant__a1aeb9_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_number'], name='sales_sale_nu_ee8c51_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='sales_created_dbdf91_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_offline', 'synced_at'], name='sales_is_offl_b4ddc4_idx'),
        ),
        migrations.AddIndex(
            model_name='shopproductcost',
            index=models.Index(fields=['shop', 'product', 'is_active'], name='shop_produc_shop_id_c19157_idx'),
        ),
        migrations.AddIndex(
            model_name='shopproductcost',
            index=models.Index(fields=['effective_from', 'effective_to'], name='shop_produc_effecti_fc802d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopproductcost',
            unique_together={('shop', 'product', 'batch', 'effective_from')},
        ),
    ]
